name: CI

on:
  push:
    branches:
      - main

jobs:
  helm-lint:
    name: "Helm Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Execute Gradle Tasks
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.3
        arguments: k8sResource k8sHelm
    - name: Run helm lint
      run: helm lint build/jkube/helm/spring-boot-template/kubernetes/
  java-unit-tests:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Execute Gradle Tasks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          arguments: spotlessCheck test jacocoReport bootJar
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: build/libs
          retention-days: 7
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: build/jacoco
          retention-days: 7
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
            name: coverage-reports
            path: build/reports
            retention-days: 7

